### ISSUE TITLE
meta issues - add them here! 

### ISSUE THREAD

**Issue by mdsumner** [mdsumner/raster-rforge#1]
Found a raster bug, list it here!  Please take the time to craft more detailed bug reports, but check the issues first.

**Comment by mdsumner** [comment]
AP reports

```
I found when I cropped my brick the time stamps changed from numeric to character. A bug perhaps? I was not sure how to report it.
 
 
ssh_brick <- brick("...ufront.nc")
> str(ssh_brick@z[[1]])
num [1:1199(1d)] 15709 15716 15723 15730 15737 ...
> ssh_brick <- crop(x=ssh_brick, y=maparea_longlat, snap='out')
> str(ssh_brick@z[[1]])
chr [1:1199(1d)] "15709" "15716" "15723" "15730" "15737" "15744" "15751" "15758" "15765" "15772" "15779" "15786" "15793" "15800" "15807" "15814" ...
 ```

**Comment by mdsumner** [comment]
Reported by email  2016-04-16

```R
For RasterLayer extract passes to .readCells, which is slow compared to the inMemory performance for a single-layer RasterBrick, which just indexes @data@values. 

You can see the difference in performance: 

library(raster)
r <- disaggregate(raster(volcano), fact = 25)
if (fromDisk(r)) r <- readAll(r)
b <- brick(r)
if (fromDisk(b)) b <- readAll(b)

cells <- sample(ncell(r), 1e6)
 system.time(extract(r, cells))
#   user  system elapsed 
#   0.53    0.11    0.64 
 system.time(extract(b, cells))
#   user  system elapsed 
#   0.17    0.00    0.17 


The behaviour for RasterLayer could really benefit from the same shortcut taken for a RasterBrick. 
```

**Comment by mdsumner** [comment]
slow extract through tiled GDAL source

```

## 1) code to create large test GeoTIFFs
library(raster)

r <- raster(ncol = 32768, nrow = 21600)
r[] <- seq(ncell(r))

writeRaster(r, "tiled.tif", options = c("TILED=YES", "COMPRESS=NONE"))
writeRaster(r, "notile.tif", options = c("TILED=NO", "COMPRESS=NONE"))

## 2) extraction code is slow for tiled tif

library(raster)
x <- cbind(runif(10000), runif(10000))
tiled <- raster("tiled.tif")
notile <- raster("notile.tif")

system.time(extract(tiled, x))
system.time(extract(notile, x))
```

**Comment by mdsumner** [comment]
Issue with stack (maybe like the SW one)

https://stackoverflow.com/questions/44295842/r-raster-cover-function-error-with-landsat-stacks

**Comment by lwasser** [comment]
thank you @mdsumner the stack issue would be nice to resolve. The use case is you have a landsat scene with many bands and you want to replace cloud covered pixels from pixels in a less cloudy scene.  You'd want to do it for each band in the stack. Oddly it works just fine if i create a stack in R (see the SO post). but it does not work with real data. It may be partially due to extent issues.

**Comment by apc53c** [comment]
`raster::subs` fails when different `by` (key) values have the same `which` (replacement) value, and `by` is a column name that is NOT the first column.

Reproducible example (raster 2.5-8):

```
r = raster::raster(nrows = 1, ncols = 1, vals = 5) # A one-cell raster.

# A successful use of subs:
succeeds_df = data.frame(by_col = c(4, 5, 6), which_col = c(40, 50, 40))
raster::subs(r, succeeds_df, by = "by_col", which = "which_col") # Works.

# Now try with a data frame in which by_col is not first column.
fails_df = data.frame(another_col = c(400, 500, 600), by_col = c(4, 5, 6), which_col = c(40, 50, 40))
raster::subs(r, fails_df, by ="by_col", which = "which_col")
# Error in .local(x, y, ...) : duplicate "by" values not allowed
```

I believe the issue is these lines of `raster::subs`:
```
y <- y[, c(by, which)]
tt <- table(y[, by])
```
By the time they are reached, `by` is the NUMBER of the by column. The first of these two lines changes the column numbers of `y`, but the second line uses the column numbers as if that hadn't happened. This is fine only if `by` was the first column.

**Comment by mdsumner** [comment]
@andycraig I don't actually understand this, the `r` has only one value so what is supposed to happen? Can you please pursue at https://github.com/rspatial/raster

**Comment by andycraig** [comment]
@mdsumner I have created issue rspatial/raster#17, with a revised example that is hopefully a bit clearer.
